gmchangerpermgm0: permissions.gm0
gmchangerpermgm1: permissions.gm1
gmchangerpermgm2: permissions.gm2
gmchangerpermgm3: permissions.gm3
permchatclear: permissions.chatclear
permchatrules: permissions.chatrules
anniWorlds:
  - world
  - Saharia
  - Coastal
  - Canyon
chatrules:
  flood: '&7Saying &n1&r&7 or more letters constantly and it can also be saying different characters that intended to flood the chat. This can result in a &l&42-4 hour mute! &c(Depends on how severe)'
  spam: '&7Spamming &n3 sentences or phrases&r&7 / &nCountdown&4&7 spamming (3,2,1...) in the chat can result in a &l&42-4 hour mute! &c(Depends on how severe)'
  caps: '&7Capitalizing &n&l4 or more words&r&7 / Capitalizing more than &n15 characters&r&7. This can result in a &l&41-2 hour mute! &c(Depends on how severe)'
  hackusating: '&7Accusing someone of &nhacking&r&7. Thus, will lower the chances of Staff to ban them. Players who accuse must use /helpop! This can result in a &l&46 hour mute!'
  arguing: '&7Someone &lconstantly contradicting what someone says &r&7/Someone &l&nprotesting a punishment that has been given to them&r&7 (Make an unban/unmute request at our forums!). This will result in a &l&412 hour mute&r&7!'
  chattrolling: '&n&7Intentionally&r &7saying things that are meant to &nconfuse &r&7or &nmislead players. &r&7| &nImpersonating a Staff member&r&7. This can result in a &c(Not showed in the guidelines, confirming it asap!)'
  askingstaffforthings: '&7Asking a Staff member who is able to &nspawn in items and/or money for a player&r&7. This can result in a l42-4 hour mute! &c(Depends on how severe)'
  advertisement: '&7Asking &nplayers to join a server &r&7via mentioning the servers name in &npublic &r&7conversation or by &nprivate &r&7messaging an &lIP&r&7. This can result in a &n&l&4PERMANENT &7ban!'
  swearing: '&7Cussing/Cursing/Swearing/being rude to a player with &nintent to hurt their &n&lfeelings&r&7. This can result in a &l&424 hours/36 hours/3 day mute! &c(Depends on how severe)'
  harassment: '&7Repeatedly being rude to a player with intent to &nhurt their &n&lfeelings&r&7. This can result in a &l&424 hour/36 hour/3 day mute! &c(Depends on how severe)'
  serverdis: '&7Giving the &lserver a &nbad name&r&7. &r&7If you see someone doing/did this, &lplease report at our forums or on discord &nimmediately!&r&7 This can result in a &l&4MUTE &7or a &l&4BAN.'
  staffdis: '&7Giving a &lStaff member/the Staff team a &nbad name&r&7. &r&7If you see someone doing/did this, &lplease report at our forums or on discord &nimmediately!&r&7 This can result in a &l&4MUTE &7or a &l&4BAN.'
  bypassingfilter: '&7Finding a way to use words that are &lfiltered/Using other &nvulgar words&r&7 that are not filtered but &lSHOULD &r&7be. This includes swearing in /msg! This can result in a &l&4mute! &c(Depends on how severe)'
  ddos: '&7Threatening a player/the server to be shut down/to put down someones internet/the server. This &n&lWILL&7 result in a &l&4PERMANENT&lban.'
  threathack: '&7Threatening a player/the server to be &lhacked. This &n&lWILL&4&7 result in a &l&4PERMANENT &lban.'
  inappb: '&7Saying something in chat that has &lsexual or generally inappropriate content&r&7. This can result in a &l&48-12 hour mute! &c(Depends on how severe)'