name: StaffMode
main: me.NinetyNine.staff.Staff
version: 0.1
author: NinetyNine
softdepend: [ProtocolLib, GCBanz]
description: A Staff Mode plugin.
commands:
  staff:
    usage: /<command>
    description: Toggles staff mode.
    permissions: staffmode.toggle
  unstaff:
    usage: /<command>
    description: Unstaffs a player.
    permissions: staffmode.unstaff
permissions:
  staffmode.toggle:
    default: false
    admin: true
  staffmode.gmsp:
    default: false
    admin: true
  staffmode.chatrules:
    default: false
    admin: true
    mod: true
    helper: true
  staffmode.chatrules.set:
    default: op
  staffmode.unstaff:
    default: op
  staffmode.joinbypass:
    default: op
  staffmode.quitbypass:
    default: op
  staffmode.vanishbypass:
    default: op
  staffmode.addworld:
    default: op
  staffmode.removeworld:
    default: op
  staffmode.worldlist:
    default: op