name: StaffMode
main: me.NinetyNine.staff.Staff
version: 0.1
author: NinetyNine
softdepend: [ProtocolLib, GCBanz, Atials]
description: A Staff Mode plugin.
commands:
  staff:
    usage: /<command>
    description: Toggles staff mode.
    permissions: staffmode.toggle
  unstaff:
    usage: /<command>
    description: Unstaffs a player.
    permissions: staffmode.unstaff
permissions:
  staffmode.toggle:
    default: op
    admin: true
    helper: false
    mod: false
    guide: false
  staffmode.help:
    default: op
    admin: true
    helper: false
    mod: true
    guide: true
  staffmode.gmsp:
    default: op
    admin: true
    mod: false
    helper: false
    guide: false
  staffmode.chatrules:
    default: op
    admin: true
    mod: true
    helper: true
    guide: true