package me.NinetyNine.staff.chatrules.utils;

public enum ExampleType {
	FLOOD, RANDOMCS, SPAM, COUNTSPAM, CAPS, ACCUSE, ARGUE, CHATT, CHATTSTAFF, ASKSTAFF, ADV, YTADV, SWEAR, SWEAR2, SWEAR3, HARASSMENT, STAFF, SERVER, BYPASS, DDOS, HACK, INAPP;
}
