package me.NinetyNine.staff.chatrules.utils;

public enum RuleType {
	FLOOD, SPAM, CAPS, HACKUSATING, ARGUING, CHAT_TROLLING, CHAT_TROLLING_STAFF, ASKING_STAFF_FOR_ITEMS, ADVERTISEMENT, YOUTUBE_ADVERTISEMENT, SWEARING, SWEARING_2, SWEARING_3, HARASSMENT, STAFFDIS, SERVERDIS, BYPASSING_FILTER, DDOS, THREATHACK, INAPPB;
}
